spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cadastro_profissionais
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect